version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Pre-build phase completed on `date`
  build:
    commands:
      - echo Build started on `date`
      - echo Building the application...
      # Add your build commands here
      - echo "Running tests..."
      - echo "Building artifacts..."
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Post-build phase completed

artifacts:
  files:
    - '**/*'
  name: build-artifacts-$(date +%Y-%m-%d)
